version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_USER=passrefa"
      - "DATABASE_PASSWORD=ebmtPpxbnkOe7DZqjHKhLgn3smB5K066"
    env_file:
      - ".env"
    volumes:
      - ".:/usr/src/app"
    links:
      - "db"
  db:
    image: postgres:12-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - "POSTGRES_USER=passrefa"
      - "POSTGRES_PASSWORD=ebmtPpxbnkOe7DZqjHKhLgn3smB5K066"